### ISSUE TITLE
"Good enough" version for first release

### ISSUE THREAD

**Issue by xrotwang** [lexibank/tls#1]
We'd need a "good enough" first release of this dataset, considering that it will be part of upcoming projects. Right now, no valid CLDF is available.

**Comment by tresoldi** [comment]
There was some Concepticon review pending, the incomplete output was intentional. I'll take care of it.

**Comment by tresoldi** [comment]
I guess this issue can now be closed, right? The dataset should be part of any major concepticon review, of course, but the data has even been released already.
