### ISSUE TITLE
Fix value column cleaning process

### ISSUE THREAD

**Issue by chrzyki** [lexibank/tls#11]
E.g. see Kimbunga-1060_prepare-1, the value `ku(yokola)` is cleaned to `ku`, whereas `ku` just appears to be a verbal prefix (or `to`?) and the form should be `yokola`.

**Comment by chrzyki** [comment]
Likewise, kimb1242 gets split incorrectly, i.e. verbs seem to be listed as `verb, uxu-`, where `uxu-` gets a separate entry each time it appears.

**Comment by tresoldi** [comment]
Thanks, I am checking it.

**Comment by tresoldi** [comment]
This is harder to fix than just setting `strip_inside_brackets` to False, as we can have alternative forms (such as `kigingi (pl.vigingi)`), sub-glosses (`ku-buma (lion)`), long descriptions (`tuta (verb of carrying the things and piling them)`), grammar annotation (`mgosi [+ poss.], mkeku [+ poss.]`), and actual linguistic material which is not clearly part of the lexeme (such as objects of verbs, perhaps as a translation of the elicitation).

In a perfect scenario we would need to manually confirm each entry with a bracket, perhaps overriding from `lexemes.csv`. Not entirely sure about how to proceed...

**Comment by chrzyki** [comment]
The situation for the `tls` data is probably somewhat similar to IDS the need for outsourcing the processing to a separate package: https://github.com/intercontinental-dictionary-series/idspy/blob/4354aa48fe6504d140b66322ddcab28af7cad6ae/src/idspy/__init__.py#L165

**Comment by xrotwang** [comment]
Hm, I don't think IDS should be a model here. IDS is still being added to and also bigger than TLS. So I'd say here, we should still operate within the lexibank framework, e.g. list problematic lexemes explicitly in `etc/lexemes.csv`.

**Comment by xrotwang** [comment]
Explicitly listing problematic lexemes also seems the only solution which is "backwards compatible", i.e. only fixes one explicit problem with no side effects.

**Comment by LinguList** [comment]
Yes, and programmatically, it is not much more time-consuming than
creating complex regexes that might capture things, but since one never
really looks at the major part of the data, this would then not be
checked. I'd start by counting the number of brackets in the data. If
it's 1000 I'd even propose to correct them manually...

**Comment by tresoldi** [comment]
I was checking the data in more detail, and it makes no sense to try to fix everything in code. We have 14,675 forms (out of 130,493) that have either parentheses or brackets (and yes, in a handful of cases both), and only some of the patterns can be captured in code (unless I fill the script with unreadable nested `if`s).

My proposed solution is to first treat what can be treated in code (for example, removing the `"(pl."` initial substrings for all the forms with a plural, which accounts for 1,206 cases, or all the `cf.`), collect common material that can be removed (such as `"(see below")`), and only then start treating the remaining cases with `lexemes.csv`. I have no idea how many entries it would be or how long it would take, but at least for the first part data quality could be improved somewhat quickly.

**Comment by LinguList** [comment]
Sounds reasonable.

**Comment by tresoldi** [comment]
Good, will start work on a branch.

**Comment by tresoldi** [comment]
Ok, I have started work on branch [`improve_forms`](https://github.com/lexibank/tls/tree/improve_forms), will make a PR once ready.

Just a couple of minutes solving some issues already brought the number of problematic forms down to half, to 7,679.

**Comment by xrotwang** [comment]
Sounds good! Once we are in the 3% range that's as good or bad as IDS, which I'd consider the benchmark here.

**Comment by tresoldi** [comment]
PR at https://github.com/lexibank/tls/pull/12
