### ISSUE TITLE
Add source

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/tls#2]
@article{NursePhillipson1975,
  journal = {KiSwahili},
  number  = {2},
  pages   = {1-28},
  title   = {The North-East Bantu Languages of Tanzania and Kenya: a Classification},
  volume  = {45},
  year    = {1975},
  author  = {Nurse, D. and G. Phillipson}
  note={\url{Available on CBOLD http://www.cbold.ish-lyon.cnrs.fr/Docs/TLSinfo.html}}
}

**Comment by tresoldi** [comment]
Already added.
