### ISSUE TITLE
Gweno and Gweno1

### ISSUE THREAD

**Issue by chrzyki** [lexibank/tls#6]
Gweno and Gweno1 are identical as far as I can tell. They're also like this in the CLICS2 release:

- https://clics.clld.org/languages/lexibank-tls-gweno
- https://clics.clld.org/languages/lexibank-tls-gweno1

Gweno1 is neither listed in the [field names](http://www.cbold.ish-lyon.cnrs.fr/Docs/TLSLANGS.html) nor in the [original source](http://www.cbold.ish-lyon.cnrs.fr/Load.aspx?Langue=TLS&Type=Text&Fichier=TLS.NursePhillipson1975.txt). Gweno1 does, however, appear in [our raw data dump](https://github.com/lexibank/tls/blob/master/raw/tls.txt) for some reason. How to proceed? Just kick it out? Am I missing something?

(and thanks to @natalia-morozova for pointing this out)

**Comment by chrzyki** [comment]
Ah, there is a 'difference' between the `txt` and the `dbf` they provide on their site; the `txt` doesn't have Gweno1, the `dbf` does have it. Still identical, though. :)

**Comment by tresoldi** [comment]
Hm... I should have caught it when preparing the dataset...

**Comment by tresoldi** [comment]
Fixed on `pylexibank2` branch: https://github.com/lexibank/tls/commit/5c2d2b25b5e2b3cfd3cbeeaabfdb4f779f5f1127
